
import { FormulaData, CalculationResult, ExplanationData } from '../types';

export const generatePDFReport = (
  formula: FormulaData,
  inputs: Record<string, number>,
  result: CalculationResult,
  explanation?: ExplanationData | null
) => {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to generate the report.');
    return;
  }

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>AI Math Studio Report - ${formula.title}</title>
        <style>
          body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #1e293b; max-width: 800px; margin: 0 auto; line-height: 1.6; }
          h1 { color: #0f172a; border-bottom: 2px solid #0f172a; padding-bottom: 10px; margin-bottom: 5px; }
          .meta { margin-bottom: 40px; color: #64748b; font-size: 0.9em; }
          .section { margin-bottom: 30px; }
          .result-box { background: #f8fafc; border: 1px solid #e2e8f0; padding: 25px; border-radius: 12px; margin: 20px 0; text-align: center; }
          .result-val { font-size: 2.5em; font-weight: bold; color: #0891b2; }
          .result-unit { font-size: 0.5em; color: #64748b; margin-left: 5px; }
          .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 15px; }
          .input-item { background: #f1f5f9; padding: 10px; border-radius: 8px; }
          .label { font-weight: bold; font-size: 0.75em; text-transform: uppercase; color: #64748b; display: block; margin-bottom: 4px; }
          .math-block { font-family: 'Courier New', monospace; background: #1e293b; color: #f8fafc; padding: 15px; border-radius: 8px; overflow-x: auto; }
          ul { margin-top: 5px; padding-left: 20px; }
          li { margin-bottom: 5px; }
          @media print {
            body { -webkit-print-color-adjust: exact; }
            .no-print { display: none; }
          }
        </style>
      </head>
      <body>
        <h1>${formula.title}</h1>
        <div class="meta">Generated by AI Math Studio on ${new Date().toLocaleString()}</div>
        
        <div class="section">
          <div class="label">Description</div>
          <p>${formula.description}</p>
        </div>

        <div class="section">
           <div class="label">Formula (LaTeX)</div>
           <div class="math-block">${formula.displayFormula}</div>
        </div>

        <div class="section">
          <div class="label">Inputs</div>
          <div class="grid">
            ${formula.inputs.map(inp => `
              <div class="input-item">
                <span class="label">${inp.label} (${inp.symbol})</span> 
                <strong>${inputs[inp.symbol]}</strong> ${inp.unit || ''}
              </div>
            `).join('')}
          </div>
        </div>

        <div class="result-box">
          <div class="label">Calculated Result</div>
          <div class="result-val">
            ${typeof result.value === 'number' ? result.value.toLocaleString(undefined, { maximumFractionDigits: 6 }) : result.value} 
            <span class="result-unit">${formula.resultUnit || ''}</span>
          </div>
        </div>

        ${explanation ? `
          <div class="section">
            <h2 style="font-size: 1.2em; border-bottom: 1px solid #e2e8f0; padding-bottom: 10px; margin-bottom: 15px;">AI Analysis</h2>
            <p><strong>Interpretation:</strong> ${explanation.meaning}</p>
            
            <div class="label" style="margin-top: 20px;">Step-by-Step Breakdown</div>
            <ul>
              ${explanation.steps.map(s => `<li>${s}</li>`).join('')}
            </ul>
            
            <div class="input-item" style="margin-top: 20px; background: #ecfeff; border: 1px solid #cffafe;">
               <div class="label" style="color: #0891b2;">Did you know?</div>
               <p style="margin: 0; font-style: italic; color: #155e75;">${explanation.insight}</p>
            </div>
          </div>
        ` : ''}
        
        <div style="margin-top: 60px; font-size: 0.8em; text-align: center; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 20px;">
          Report generated automatically by AI Math Studio
        </div>

        <script>
          window.onload = () => { setTimeout(() => window.print(), 500); };
        </script>
      </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
};
